[package]
name = "three_little_words"
description = "Generate random yet memorable passwords in the format [adjective adjective noun]"
version = "0.2.0"
authors = ["Ryan O'Beirne <robeirne@spoonflower.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
rand = "0.8.0"
